export enum Color {
  Raspberry = "var(--color-rasp)",
  Frost = "var(--color-frost)",
  FrostDark = "var(--color-frost-dark)",
  FrostDisabled = "var(--color-frost-disabled)",
  Sky = "var(--color-sky)",
  Space = "var(--color-space)",
  Black = "var(--color-black)",
  Spruce = "var(--color-spruce)",
  SpruceLight = "var(--color-spruce-light)",
  Apricot = "var(--color-apricot)",
  Linen = "var(--color-linen)",
  Deepwater = "var(--color-deepwater)",
  oSTEMBlue = "var(--color-ostem-blue)",
  AntiqueTeal = "var(--color-antique-teal)",
  SkyBlue = "var(--color-skyblue)",
}
